name: Build[MacOS]

on: [push]

jobs:
  build:
    name: Build packages
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and check casks
        run: |
          brew install --formula ./Formula/snowflake-cli.rb
          export PATH="/Applications/SnowflakeCLI.app/Contents/MacOS:$PATH"
          which snow        
          snow --version
          brew install --formula ./Formula/snowflake-cli.rb
          export PATH="/Applications/SnowCLI.app/Contents/MacOS:$PATH"
          which snow
          snow --version
          

