name: Build[Ubuntu]

on: [push]

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install brew
        run: |
          sudo apt update
          sudo apt-get install build-essential curl git -y
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
           eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew doctor
      - name: Install and check casks
        run: |
          brew install --debug --cask ./Casks/snowflake-cli.rb
          export PATH="/Applications/SnowflakeCLI.app/Contents/MacOS:$PATH"
          which snow        
          snow --version
          brew install --debug --cask ./Casks/snowcli.rb
          export PATH="/Applications/SnowCLI.app/Contents/MacOS:$PATH"
          which snow
          snow --version
          

